### ISSUE TITLE
Capability with other relays [feature request]

### ISSUE THREAD

**Issue by PizBernina** [dvush/check-relay-value#2]
Hi, nice tool! Any plans to further expand it to other relays?
Does a page like this https://boost-relay.flashbots.net/ even exist for other relays such as bloXroute?

**Comment by dvush** [comment]
You can specify any relay url.

Here is a list of the relays that I know:
```
flashbots            https://boost-relay.flashbots.net
bloxroute.max-profit https://bloxroute.max-profit.blxrbdn.com
bloxroute.ethical    https://bloxroute.ethical.blxrbdn.com
bloxroute.regulated  https://bloxroute.regulated.blxrbdn.com
blocknative          https://builder-relay-mainnet.blocknative.com
eden                 https://relay.edennetwork.io
manifold             https://mainnet-relay.securerpc.com
```

Also, I've been working on a new version here where it's more convenient. 
https://github.com/dvush/check-relay-value/tree/go
